language: generic

services:
    - docker

env:
    matrix:
        - PHP_VERSION=56 COMPOSER_VERSION=1.5.6
        - PHP_VERSION=56 COMPOSER_VERSION=1.6.5
        - PHP_VERSION=56 COMPOSER_VERSION=1.8.4
        - PHP_VERSION=72 COMPOSER_VERSION=1.5.6
        - PHP_VERSION=72 COMPOSER_VERSION=1.6.5
        - PHP_VERSION=72 COMPOSER_VERSION=1.8.4

script:
    - make build

deploy:
    - provider: script
      script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && make push
      on:
          branch: master

matrix:
    fast_finish: true
