language: generic

services:
    - docker

env:
    matrix:
        - PHP_VERSION=5.6 COMPOSER_VERSION=1.5.6
        - PHP_VERSION=5.6 COMPOSER_VERSION=1.6.5
        - PHP_VERSION=5.6 COMPOSER_VERSION=1.8.4
        - PHP_VERSION=7.2 COMPOSER_VERSION=1.5.6
        - PHP_VERSION=7.2 COMPOSER_VERSION=1.6.5
        - PHP_VERSION=7.2 COMPOSER_VERSION=1.8.4

script:
    - make build

matrix:
    fast_finish: true
